version: "3.8"

services:
  backend:
    image: node:18
    restart: always
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/home/node/app
    depends_on:
      - database
    ports:
      - 8000:3000
    command: sh -c "./scripts/start.sh"

  database:
    image: mariadb:10.6.14
    restart: always
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: live

  frontend:
    image: node:18
    restart: always
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/home/node/app
    ports:
      - 80:3000
    command: sh -c "./scripts/start.sh"

  static:
    image: halverneus/static-file-server
    restart: always
    volumes:
      - ./static:/web
    ports:
      - 9000:8080

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: admin
      PMA_PASSWORD: admin
    depends_on:
      - database
    ports:
      - 8080:80
