services:
  database:
    image: mariadb:10.6.14
    restart: always
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: live
    ports:
      - "3306:3306"

  static:
    image: halverneus/static-file-server
    restart: always
    volumes:
      - ./static:/web
    ports:
      - "8081:8080"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: admin
      PMA_PASSWORD: admin
    depends_on:
      - database
    ports:
      - "8080:80"
