export const enum SearchParam {
  AVG_SPEED_CHART = "avgSpeedChart",
  CATEGORY = "category",
  EDITION = "edition",
  GENDER = "gender",
  PAGE = "page",
  RACE = "race",
  RANKING_TIME = "rankingTime",
  SEARCH = "search",
  SHOW = "show",
  SHOW_AVG_SPEED = "showAvgSpeed",
  SHOW_AVG_SPEED_EVOLUTION = "showAvgSpeedEvolution",
  SHOW_HOUR_SPEED = "showHourSpeed",
  SHOW_LAP_SPEED = "showLapSpeed",
  SORT_COLUMN = "sortColumn",
  SORT_DIRECTION = "sortDirection",
  TAB = "tab",
  TIME_MODE = "timeMode",
}
