export const enum SearchParam {
  AVG_SPEED_CHART = "avgSpeedChart",
  CATEGORY = "category",
  CUSTOM_INTERVALS = "customIntervals",
  EDITION = "edition",
  FROM_RACE_TIME = "fromRaceTime",
  GENDER = "gender",
  PAGE = "page",
  RACE = "race",
  RANKING_TIME = "rankingTime",
  REGULAR_INTERVAL = "regularInterval",
  SEARCH = "search",
  SHOW = "show",
  SHOW_AVG_SPEED = "showAvgSpeed",
  SHOW_AVG_SPEED_EVOLUTION = "showAvgSpeedEvolution",
  SHOW_HOUR_SPEED = "showHourSpeed",
  SHOW_LAP_SPEED = "showLapSpeed",
  SORT_COLUMN = "sortColumn",
  SORT_DIRECTION = "sortDirection",
  SPLIT_TIMES_MODE = "splitTimesMode",
  TAB = "tab",
  TIME_MODE = "timeMode",
  TO_RACE_TIME = "toRaceTime",
}
